n1 = str(input('Digite seu nome: ')).strip()
nome = n1.split()
print('Muito prazer em conhcer !!! ')
print('Seu primeiro nome é {}'.format(nome[0]))
print('Seu ultimo nome é {}'.format(nome[len(nome)-1]))
