nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando teu nome...')
print('Seu nome em Maiusculo fica: {}\nem minusculo fica: {}'.format(nome.upper(),nome.lower()))
print('Seu nome tem: {} letras '.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras:'.format(nome.find(' ')))
